spring:
  application:
    name: thoughts-microservices
        
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      thoughtTopicName: THOUGHT_INCOMING_REQUESTS
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      
    consumer:
      group-id: THOUGHT_CONSUMER_1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      max-poll-records: 100 
      properties:
        spring:
          json:
            trusted:
              packages: io.microservices.thoughts.dto.kafkaEventsModel
  docker:
    compose:
      enabled: true
      file: C:\\Workspace\\Thought-nest\\microservices\\thoughts\\compose.yaml
  data:
    mongodb:
      host: localhost
      port: 27018
      database: thoughts-nest
      username: root
      password: secret
      authentication-database: admin
      auto-index-creation: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    hostname: localhost 
    prefer-ip-address: false
    ip-address: 127.0.0.1
    metadata-map:
      hostname: localhost

server:
  port: 3002
