spring:
  application:
    name: socialfeedbackservice
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27018/thought-nest

server:
  port: 3003

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
    ip-address: 127.0.0.1
    metadata-map:
      hostname: localhost     
