spring:
  h2:
    console:
      enabled: true
  application:
    name: authentication
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27018/thoughts-nest?authSource=admin
  docker:
    compose:
      enabled: true
      file: C:\\Workspace\\Thought-nest\\microservices\\thoughts\\compose.yaml

eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone : http://localhost:8761/eureka/
    instance:
      hostname: localhost 
      prefer-ip-address: false
      ip-address: 127.0.0.1
      metadata-map:
        hostname: localhost

auth:
  secret: somethinghjbjbjbjbjbkbjkbkjbjbjkbbkjbbkjbjbjkbkjbjkbkbjbkjbjbkbbbbjbkjbjbkjbkb


server:
  port: 3001