spring:
  cloud:
   gateway:
    routes:
      - id: authentication
        uri: lb://AUTHENTICATION
        predicates:
          - Path=/auth/**,/user/**

      - id: thoughts-microservices
        uri: lb://THOUGHTS-MICROSERVICES
        predicates:
          - Path=/thought/**

      - id: socialfeedbackservice
        uri: lb://SOCIALFEEDBACKSERVICE
        predicates:
          - Path=/socialfeedback/**
       
  application:
    name: Thoughtnest-Gateway

  docker:
    compose:
      enabled: false
      file: C:\\Workspace\\Thought-nest\\microservices\\thoughtnest-gateway\\compose.yaml

  h2:
    console:
      enabled: true
      

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 3000
